basePath: /
host: localhost:8000
info:
  contact:
    name: Wanderson Vieira
  description: Product API with auhtentication
  license:
    name: W
  termsOfService: http://swagger.io/terms/
  title: Go Expert API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
